{{- if .Values.order.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-conf
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: order
data:
  conf.yaml: |
    kitex:
      service: "{{ .Values.order.kitex.service }}"
      address: "{{ .Values.order.kitex.address }}"
      metrics_port: "{{ .Values.order.kitex.metrics_port }}"
      log_level: {{ .Values.order.kitex.log_level }}
    mysql:
      dsn: "{{ .Values.order.mysql.dsn }}"
      username: {{ .Values.order.mysql.username | quote }}
      password: {{ .Values.order.mysql.password | quote }}
      address: {{ .Values.order.mysql.address | quote }}
      port: {{ .Values.order.mysql.port }}
      database: {{ .Values.order.mysql.database | quote }}
    redis:
      address: "{{ .Values.order.redis.address }}"
      username: "{{ .Values.order.redis.username }}"
      password: "{{ .Values.order.redis.password }}"
      db: {{ .Values.order.redis.db }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: order
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gomall.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: order
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gomall.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: order
    spec:
      containers:
      - name: order
        image: "{{ .Values.order.image.repository }}:{{ .Values.order.image.tag }}"
        ports:
        - containerPort: {{ .Values.order.service.targetPort }}
        env:
        - name: GO_ENV
          value: {{ .Values.global.goEnv | quote }}
        volumeMounts:
        - name: conf
          mountPath: /app/conf/{{ .Values.global.goEnv }}/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: conf
        configMap:
          name: order-conf
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    {{- include "gomall.labels" . | nindent 4 }}
    app.kubernetes.io/component: order
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.order.service.port }}
    targetPort: {{ .Values.order.service.targetPort }}
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: {{ include "gomall.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: order
{{- end }}
