apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: gomall
  labels:
    app: checkout
spec:
  type: ClusterIP
  ports:
  - port: 8884
    targetPort: 8884
    protocol: TCP
    name: grpc
  selector:
    app: checkout
