apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-conf
data:
  conf.yaml: |
    kitex:
      service: "checkout"
      address: ":8884"
      metrics_port: ":9994"
      log_level: info
    nats:
      url: "nats://nats:4222"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: buwandocker/checkout:lab2
        ports:
        - containerPort: 8884
        env:
        - name: GO_ENV
          value: "dev"
        volumeMounts:
        - name: conf
          mountPath: /app/conf/dev/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: conf
        configMap:
          name: checkout-conf
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  labels:
    app: checkout
spec:
  type: ClusterIP
  ports:
  - port: 8884
    targetPort: 8884
    protocol: TCP
    name: http
  selector:
    app: checkout
