apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-config
  namespace: gomall
data:
  conf.yaml: |
    kitex:
      service: "checkout"
      address: ":8884"
      metrics_port: ":9994"
      log_level: info
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50

    nats:
      url: "nats://nats.default.svc.cluster.local:4222"

    rate_limiter:
      enabled: true
      bucket_size: 10
      rate: 2
