apiVersion: v1
kind: Service
metadata:
  name: email
  namespace: gomall
  labels:
    app: email
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: grpc
  selector:
    app: email
