apiVersion: v1
kind: ConfigMap
metadata:
  name: email-conf
data:
  conf.yaml: |
    kitex:
      service: "email"
      address: ":8888"
      log_level: info
    nats:
      url: "nats://nats:4222"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: buwandocker/email:lab2
        ports:
        - containerPort: 8888
        env:
        - name: GO_ENV
          value: "dev"
        volumeMounts:
        - name: conf
          mountPath: /app/conf/dev/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: conf
        configMap:
          name: email-conf
---
apiVersion: v1
kind: Service
metadata:
  name: email
  labels:
    app: email
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: email
