apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  namespace: gomall
  labels:
    app: email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
      - name: email
        image: buwandocker/email:lab2
        ports:
        - containerPort: 8888
          name: grpc
        volumeMounts:
        - name: config
          mountPath: /app/conf/dev
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: email-config
