apiVersion: v1
kind: ConfigMap
metadata:
  name: order-conf
data:
  conf.yaml: |
    kitex:
      service: "order"
      address: ":8885"
      metrics_port: ":9995"
      log_level: info
    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      username: gomall
      password: gomall123
      address: mysql
      port: 3306
      database: order
    redis:
      address: "redis:6379"
      username: ""
      password: ""
      db: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: buwandocker/order:lab2
        ports:
        - containerPort: 8885
        env:
        - name: GO_ENV
          value: "dev"
        volumeMounts:
        - name: conf
          mountPath: /app/conf/dev/conf.yaml
          subPath: conf.yaml
      volumes:
      - name: conf
        configMap:
          name: order-conf
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  type: ClusterIP
  ports:
  - port: 8885
    targetPort: 8885
    protocol: TCP
    name: http
  selector:
    app: order
