apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: gomall
  labels:
    app: order
spec:
  type: ClusterIP
  ports:
  - port: 8885
    targetPort: 8885
    protocol: TCP
    name: grpc
  selector:
    app: order
