apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: gomall
  labels:
    app: user
spec:
  type: ClusterIP
  ports:
  - port: 8882
    targetPort: 8882
    protocol: TCP
    name: grpc
  selector:
    app: user
