apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: gomall
data:
  conf.yaml: |
    kitex:
      service: "user"
      address: ":8882"
      metrics_port: ":9992"
      log_level: debug
      log_file_name: "log/kitex.log"
      log_max_size: 10
      log_max_age: 3
      log_max_backups: 50

    mysql:
      dsn: "%s:%s@tcp(%s:%d)/%s?charset=utf8mb4&parseTime=True&loc=Local"
      username: root
      password: root123
      address: mysql.default.svc.cluster.local
      port: 3306
      database: user

    rate_limiter:
      enabled: false
      bucket_size: 10
      rate: 5
